server:
  port: 8080

debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  webflux:
    codec:
      max-in-memory-size: 2MB
  devtools:
    livereload:
      port: 35730
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cbz?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: cbz
    password: cbzse

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    com.swm.mvp: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web.client.RestTemplate: debug